kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: webdav-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: webdav-plugin
          image: scodeman/webdav-csi-driver:latest
          imagePullPolicy: Always
        
